# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(default=0)),
                ('weight', models.FloatField(default=0)),
            ],
        ),
    ]
