# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributes',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
