# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imc', '0002_auto_20180410_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributes',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
